In [1]:
# Initial Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [2]:
 # Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path("C:/Users/panka/Documents/Homework/Module_13_Challenge/applicants_data.csv"))

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN",'NAME']).copy()

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [6]:
 # Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [7]:
 # Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [8]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

C:\Users\panka\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [9]:
# Create a DataFrame with the columnns containing numerical variables from the original dataset
numerical_variables_df = applicant_data_df.drop(columns = categorical_variables)

# Review the DataFrame
numerical_variables_df.head()

   STATUS  ASK_AMT  IS_SUCCESSFUL
0       1     5000              1
1       1   108590              1
2       1     5000              0
3       1     6692              1
4       1   142590              1

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df_new = pd.concat(
    [
        numerical_variables_df,
        encoded_df
    ],
    axis=1
)

# Review the Dataframe
encoded_df_new.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
# Using the preprocessed data, create the features (X) and target (y) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset

# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df_new["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [12]:
 # Define features set X by selecting all columns but IS_SUCCESSFUL
X =  encoded_df_new.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [13]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [14]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [15]:
#  Compile and Evaluate a Binary Classification Model Using a Neural Network

In [16]:
 # Define the the number of inputs (features) to the model
number_input_features =  len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [17]:
 # Define the number of neurons in the output layer
number_output_neurons = 1

In [18]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [19]:
 # Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [20]:
 # Create the Sequential model instance
nn = Sequential()

In [21]:
 # Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [22]:
 # Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [23]:
 # Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [24]:
 # Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

In [25]:
 # Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [26]:
 # Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5738 - accuracy: 0.7193
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5525 - accuracy: 0.7306
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7308
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7324
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7332
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5448 - accuracy: 0.7339
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7338
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7346
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7357
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7358
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7361
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7365
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7355
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7369
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7370
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7365
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7371
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7371
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7378
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7384
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7385
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5366 - accuracy: 0.7376
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7389
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7382
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7394
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5358 - accuracy: 0.7392
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7388
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7383
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5348 - accuracy: 0.7403
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7393
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7390
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7398
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7399
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5334 - accuracy: 0.7403
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7397
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7398
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5338 - accuracy: 0.7393
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5332 - accuracy: 0.7405
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5331 - accuracy: 0.7400
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7410
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7408
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5325 - accuracy: 0.7393
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7409
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7413
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7407
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7413
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7419
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7407
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7401
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7412

In [27]:
 # Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5556 - accuracy: 0.7310 - 607ms/epoch - 2ms/step
Loss: 0.5555784702301025, Accuracy: 0.7309620976448059

In [28]:
# Save model in JSON format
nn_json = nn.to_json()

# Set the model's file path
file_path = Path("C:/Users/panka/Documents/Homework/Module_13_Challenge/model.json")

# Write the model to the the file 
with open(file_path, "w") as json_file:
    json_file.write(nn_json)

# Export your model to a HDF5 file
file_path = Path("C:/Users/panka/Documents/Homework/Module_13_Challenge/model.h5")

# Save the weights to the file path
nn.save_weights(file_path)

In [29]:
# Optimise the Neural Network Model

In [30]:
#  Alternative Model 1 (Adding another layer to the existing model)

 # Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [31]:
 # Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [32]:
 # Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [33]:
 # Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A1 = (hidden_nodes_layer1_A1 + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer2_A1

29

In [34]:
 # Create the Sequential model instance
nn_A1 = Sequential()

In [35]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))

# second hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer2_A1, activation="relu"))

# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 58)                6786

 dense_4 (Dense)             (None, 29)                1711

 dense_5 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

In [36]:
 # Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [37]:
 # Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5775 - accuracy: 0.7166
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5531 - accuracy: 0.7301
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7305
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7319
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7332
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7342
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7340
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7343
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7348
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7350
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7366
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7355
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7365
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7363
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7365
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7377
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7370
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7372
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7377
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7385
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7388
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7390
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7381
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7394
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7390
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7382
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7393
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7399
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7406
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7394
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7396
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7396
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7395
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7391
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7399
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7411
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5328 - accuracy: 0.7401
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5327 - accuracy: 0.7403
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5333 - accuracy: 0.7409
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7407
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7403
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7398
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5324 - accuracy: 0.7411
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7411
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5321 - accuracy: 0.7409
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7404
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7406
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7409
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5313 - accuracy: 0.7416
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5314 - accuracy: 0.7410

In [39]:
#  Alternative Model 2 (Using less nodes for hidden layer, linear activation for output layer and decreasing the no. of epochs to 20)

In [40]:
 # Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [41]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [42]:
 # Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features + 1) // 4

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

29

In [43]:
 # Create the Sequential model instance
nn_A2 = Sequential()

In [44]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A2.add(Dense(units=1, activation="linear"))


# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 29)                3393

 dense_7 (Dense)             (None, 1)                 30

=================================================================
Total params: 3,423
Trainable params: 3,423
Non-trainable params: 0
_________________________________________________________________

In [45]:
 # Compile the Sequential model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [46]:
 # Fit the model using 20 epochs and the training data
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=20)

Epoch 1/20
804/804 [==============================] - 2s 2ms/step - loss: 1.7793 - accuracy: 0.6593
Epoch 2/20
804/804 [==============================] - 1s 1ms/step - loss: 1.0606 - accuracy: 0.7025
Epoch 3/20
804/804 [==============================] - 1s 1ms/step - loss: 0.9356 - accuracy: 0.7181
Epoch 4/20
804/804 [==============================] - 1s 2ms/step - loss: 0.9419 - accuracy: 0.7170
Epoch 5/20
804/804 [==============================] - 1s 2ms/step - loss: 0.9791 - accuracy: 0.7123
Epoch 6/20
804/804 [==============================] - 1s 2ms/step - loss: 1.0011 - accuracy: 0.7082
Epoch 7/20
804/804 [==============================] - 1s 2ms/step - loss: 1.0288 - accuracy: 0.7061
Epoch 8/20
804/804 [==============================] - 2s 2ms/step - loss: 1.2396 - accuracy: 0.6862
Epoch 9/20
804/804 [==============================] - 2s 2ms/step - loss: 0.9315 - accuracy: 0.7171
Epoch 10/20
804/804 [==============================] - 2s 2ms/step - loss: 0.9369 - accuracy: 0.7189
Epoch 11/20
804/804 [==============================] - 1s 2ms/step - loss: 0.8657 - accuracy: 0.7216
Epoch 12/20
804/804 [==============================] - 1s 2ms/step - loss: 1.0405 - accuracy: 0.7074
Epoch 13/20
804/804 [==============================] - 1s 2ms/step - loss: 1.0232 - accuracy: 0.7106
Epoch 14/20
804/804 [==============================] - 1s 2ms/step - loss: 1.0299 - accuracy: 0.7100
Epoch 15/20
804/804 [==============================] - 1s 2ms/step - loss: 1.0759 - accuracy: 0.7063
Epoch 16/20
804/804 [==============================] - 1s 2ms/step - loss: 1.1707 - accuracy: 0.7023
Epoch 17/20
804/804 [==============================] - 1s 2ms/step - loss: 1.0716 - accuracy: 0.7042
Epoch 18/20
804/804 [==============================] - 1s 2ms/step - loss: 0.8890 - accuracy: 0.7135
Epoch 19/20
804/804 [==============================] - 1s 2ms/step - loss: 0.9244 - accuracy: 0.7100
Epoch 20/20
804/804 [==============================] - 1s 2ms/step - loss: 0.8619 - accuracy: 0.7242

In [48]:
#  Alternative Model 3 (Using more nodes for hidden layer and increasing the no. of epochs to 100))

In [49]:
 # Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [50]:
# Define the number of neurons in the output layer
number_output_neurons_A3 = 1

In [51]:
 # Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A3 = number_input_features

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A3

116

In [52]:
 # Create the Sequential model instance
nn_A3 = Sequential()

In [53]:
# First hidden layer
nn_A3.add(Dense(units=hidden_nodes_layer1_A3, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A3.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_A3.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 116)               13572

 dense_9 (Dense)             (None, 1)                 117

=================================================================
Total params: 13,689
Trainable params: 13,689
Non-trainable params: 0
_________________________________________________________________

In [54]:
 # Compile the Sequential model
nn_A3.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [55]:
 # Fit the model using 100 epochs and the training data
fit_model_A3 = nn_A3.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5798 - accuracy: 0.7186
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5576 - accuracy: 0.7286
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5555 - accuracy: 0.7292
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5530 - accuracy: 0.7301
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7306
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5510 - accuracy: 0.7311
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7304
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5484 - accuracy: 0.7317
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5475 - accuracy: 0.7318
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7324
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5468 - accuracy: 0.7302
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7318
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7334
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7331
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7326
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7350
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7335
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7324
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7337
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7343
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7341
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7358
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7351
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7347
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7352
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7352
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7345
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7357
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7353
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7360
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7356
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7363
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7360
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7365
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7374
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7369
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7362
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7368
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7371
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7369
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7365
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7376
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7365
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7373
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7359
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7367
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7371
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7374
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7369
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7372
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7368
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7369
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7373
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7378
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7386
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7386
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7382
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7378
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7368
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7383
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7381
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7391
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7389
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7371
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7383
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7377
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7384
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7379
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7389
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7377
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7379
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7397
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7386
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7391
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7392
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7388
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7394
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7365
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7383
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5349 - accuracy: 0.7391
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7391
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7390
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7388
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7389
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7381
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7382
Epoch 88/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5348 - accuracy: 0.7394
Epoch 89/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5347 - accuracy: 0.7384
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7392
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7399
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5343 - accuracy: 0.7385
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7397
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7373
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7389
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7397
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7395
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7392
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7402
Epoch 100/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5342 - accuracy: 0.7387

In [56]:
# Display the accuracy scores achieved by each model, and compare the results

In [58]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5556 - accuracy: 0.7310 - 333ms/epoch - 1ms/step
Loss: 0.5555784702301025, Accuracy: 0.7309620976448059

In [59]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5580 - accuracy: 0.7319 - 339ms/epoch - 1ms/step
Loss: 0.5579661130905151, Accuracy: 0.7318950295448303

In [60]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.8650 - accuracy: 0.7224 - 458ms/epoch - 2ms/step
Loss: 0.8650399446487427, Accuracy: 0.722449004650116

In [61]:
print("Alternative Model 3 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A3.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 3 Results
268/268 - 0s - loss: 0.5750 - accuracy: 0.7327 - 454ms/epoch - 2ms/step
Loss: 0.5750026702880859, Accuracy: 0.7327113747596741

In [62]:
# Save each of your alternative models as an HDF5 file

In [66]:
# Set the file path for the first alternative model
file_path = Path("C:/Users/panka/Documents/Homework/Module_13_Challenge/Alternativemodel1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [67]:
# Set the file path for the second alternative model
file_path = Path("C:/Users/panka/Documents/Homework/Module_13_Challenge/Alternativemodel2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)

In [68]:
# Set the file path for the third alternative model
file_path = Path("C:/Users/panka/Documents/Homework/Module_13_Challenge/Alternativemodel3.h5")

# Export your model to a HDF5 file
nn_A3.save(file_path)